In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [8]:
df = pd.read_csv('/content/creditcardfraud.csv')

In [9]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [11]:
df.shape

(126842, 31)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126842 entries, 0 to 126841
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    126842 non-null  int64
 1   V1      126842 non-null  float64
 2   V2      126842 non-null  float64
 3   V3      126842 non-null  float64
 4   V4      126842 non-null  float64
 5   V5      126842 non-null  float64
 6   V6      126842 non-null  float64
 7   V7      126842 non-null  float64
 8   V8      126842 non-null  float64
 9   V9      126841 non-null  float64
 10  V10     126841 non-null  float64
 11  V11     126841 non-null  float64
 12  V12     126841 non-null  float64
 13  V13     126841 non-null  float64
 14  V14     126841 non-null  float64
 15  V15     126841 non-null  float64
 16  V16     126841 non-null  float64
 17  V17     126841 non-null  float64
 18  V18     126841 non-null  float64
 19  V19     126841 non-null  float64
 20  V20     126841 non-null  float64
 21  V21     126841 non-null  float64
 22  V22     126841 non-null  float64
 23  V23     126841 non-null  float64
 24  V24     126841 non-null  float64
 25  V25     126841 non-null  float64
 26  V26     126841 non-null  float64
 27  V27     126841 non-null  float64
 28  V28     126841 non-null  float64
 29  Amount  126841 non-null  float64
 30  Class   126841 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 30.0 MB

In [14]:
df['Class'].value_counts()

Class
0.0    126581
1.0       260
Name: count, dtype: int64

In [15]:
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [17]:
print(legit.shape)
print(fraud.shape)

(126581, 31)
(260, 31)

In [19]:
legit.Amount.describe()

count    126581.000000
mean         93.139733
std         252.565956
min           0.000000
25%           6.540000
50%          24.950000
75%          83.470000
max       19656.530000
Name: Amount, dtype: float64

In [20]:
fraud.Amount.describe()

count     260.000000
mean      116.897692
std       246.750422
min         0.000000
25%         1.000000
50%        10.685000
75%       100.367500
max      1809.680000
Name: Amount, dtype: float64

In [21]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,48895.798943,-0.239172,-0.009307,0.692569,0.139343,-0.276066,0.087639,-0.103912,0.059184,-0.079909,...,0.042216,-0.039029,-0.114771,-0.034243,0.012073,0.130520,0.026269,-0.000316,0.001829,93.139733
1.0,41834.653846,-5.671074,3.981496,-7.244578,4.545756,-4.025447,-1.498972,-5.996932,1.531671,-2.627267,...,0.241923,1.274635,-0.321896,-0.113359,-0.107386,0.199859,0.058654,0.497977,0.081654,116.897692

In [22]:
legit_sample = legit.sample(n=260)

In [27]:
n_df= pd.concat([legit_sample, fraud], axis=0)

In [28]:
n_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
51806,45128,1.338165,-0.101240,-0.468997,-1.535507,-0.215282,-1.454499,0.419194,-0.409258,0.912709,...,-0.389075,-1.091698,0.018388,-0.106323,0.488153,-0.310773,-0.025512,0.010349,28.95,0.0
121363,76166,-5.819565,3.525300,-1.310711,-1.668870,-4.539966,-0.741649,-3.713584,4.206170,-0.785885,...,0.016836,-0.068477,0.265367,0.398702,0.501423,1.117823,0.000967,0.021919,17.50,0.0
108540,70954,1.169208,-0.187962,0.610267,0.088065,-0.676074,-0.450382,-0.320150,-0.003756,0.403196,...,0.027159,0.071980,0.032670,0.151015,0.111273,1.014921,-0.054572,0.011471,33.90,0.0
25213,33533,-0.103189,0.022133,-0.000971,-2.462668,1.949317,3.279976,-0.399779,0.853064,-1.564781,...,-0.018695,-0.359330,-0.091978,0.982992,0.010905,-0.444902,0.058764,0.053345,7.95,0.0
1434,1111,1.132691,-0.099536,1.006702,0.526097,-0.753368,-0.169313,-0.489722,0.072851,0.410196,...,0.044140,0.152924,0.064859,0.126463,0.088205,0.416721,0.008908,0.028402,29.54,0.0

In [30]:
n_df['Class'].value_counts()

Class
0.0    260
1.0    260
Name: count, dtype: int64

In [31]:
n_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,46661.411538,-0.126090,-0.020547,0.710357,0.200740,-0.323311,0.165574,-0.103467,0.121757,-0.083541,...,0.110039,-0.062718,-0.121129,-0.058605,-0.009765,0.176056,0.009351,0.016629,0.000659,107.109731
1.0,41834.653846,-5.671074,3.981496,-7.244578,4.545756,-4.025447,-1.498972,-5.996932,1.531671,-2.627267,...,0.241923,1.274635,-0.321896,-0.113359,-0.107386,0.199859,0.058654,0.497977,0.081654,116.897692

In [32]:
X = n_df.drop(columns='Class', axis=1)
y = n_df['Class']

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify = y,random_state=42)

In [35]:
model = LogisticRegression()

In [36]:
model.fit(X_train,y_train)

LogisticRegression()

In [39]:
y_pred = model.predict(X_test)

In [43]:
#accuracy on training data
X_train_pred = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_pred, y_train)
training_data_accuracy

0.9399038461538461

In [45]:
#accuracy on test data
X_test_pred = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_pred, y_test)
testing_data_accuracy

0.9423076923076923